(define (try-coercion type-tags args op)
  (define (try-type types-to-try type-tags args op)
    (define (coerce-list type type-tags args)
      (if (null? type-tags)
        '()
        (let ((t1 (car type-tags)))
          (let ((t1->type (get-coercion t1 type)))
            (cond (t1->type 
                    (let ((coerced-rest (coerce-list type (cdr type-tags) (cdr args))))
                      (if (not (eq? coerced-list 'error))
                        (cons (t1->type (car args)) 
                              coerced-rest))))
                  (else 'error)))
        )))
    (if (null? types-to-try)
      'error
      (let ((proc (get op (car types-to-try) (car types-to-try))))
        (if (null? proc)
          (try-type (cdr types-to-try) type-tags args op)
          (let ((coerced-list (coerce-list (car types-to-try) type-tags args)))
            (if (eq? coerced-list 'error)
              (try-type cdr(types-to-try) type-tags args)
              (apply proc coerced-list)))))))
  (let ((response (try-type type-tags type-tags args op)))
    (cond ((eq? response 'error) (error "No method for these types"))
          (else response))))

(define (apply-generic op . args)
  (let ((type-tags (map type-tag args)))
    (try-coercion type-tags args op)))
          
