(define (or-gate a b output)
  (let ((ainv (make-wire))
        (binv (make-wire))
        (andout (make-wire)))
    (inverter a ainv)
    (inverter b binv)
    (and-gate ainv binv andout)
    (inverter andout output)
    'ok))
