(define (make-account balance password password)
  (define (withdraw amount)
    (if (>= balance amount)
      (begin (set! balance (- balance amount))
             balance)
      "Insufficient Funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch m user-password)
    (if (eq? password user-password) 
      (cond ((eq? m 'withdraw) withdraw)
            ((eq? m 'deposit) deposit)
            (else (error "Unknown request -- MAKE ACCOUNT"
                         m)))
      "INCORRECT PASSWORD"))
  dispatch)
    
