(define (averager a b c)
  (let ((c make-connector)
        (d make-connector)
        (e make-connector)
        (f make-connector))
    (adder a b d)
    (constant 2 e)
    (multiplier d e f)
    (constant 2 g)
    (multiplier g c f)
    'ok))
