(load "3_33_runner.scm")
(define (celsius-fahrenheit-converter c f)
  (let ((u (make-connector))
        (v (make-connector))
        (w (make-connector))
        (x (make-connector))
        (y (make-connector)))
    (multiplier c w u)
    (multiplier v x u)
    (adder v y f)
    (constant 9 w)
    (constant 5 x)
    (constant 32 y)
    'ok))

(define (averager a b c)
  (let ((d (make-connector))
        (e (make-connector)))
    (adder a b d)
    (multiplier e c d)
    (constant 2 e)
    'ok))

(define A (make-connector))
(define B (make-connector))
(define C (make-connector))
(averager A B C)
(probe "arg#1" A)
(probe "arg#2" B)
(probe "average" C)

(set-value! A 10 'user)
(set-value! B 20 'user)

(define D (make-connector))
(define E (make-connector))
(celsius-fahrenheit-converter D E)
(probe "celsius" D)
(probe "fahrenheit" E)
(set-value! D 25 'user)
