(define (rand operation)
  (let ((x random-init))
    (cond ((eq? operation 'generate)
           (lambda ()
             (set! x (rand-update x))
             x)) 
          ((eq? operation 'reset) (lambda (v) (set! x v)))
          (else "UNKNOWN OPERATION -- RAND")
          )))
