(define (cont-frac n d k)
    (define (frac nk dk ck)
      (let ((num (n (- k ck)))
            (denom (d (- k ck)))
           )
           (if (= ck 0)
              (/ num denom)
              (/ num (+ denom (frac num denom (- ck 1))))
           )
      )
    )
    (frac 1 1 k)
)

(cont-frac (lambda (i) 1.0)
           (lambda (i) 1.0)
           1000)
